export const movieList = [
  {
    id: 1,
    name: "Rabid Grannies (Mémés cannibales, Les)",
    year: 1997,
    rating: 1.2,
    inTheaters: true,
  },
  {
    id: 2,
    name: "7 Boxes (7 cajas)",
    year: 1988,
    rating: 3.9,
    inTheaters: false,
  },
  {
    id: 3,
    name: "A Fugitive from the Past",
    year: 1964,
    rating: 1.3,
    inTheaters: false,
  },
  {
    id: 4,
    name: "Strawberry Blonde, The",
    year: 2015,
    rating: 1.8,
    inTheaters: true,
  },
  {
    id: 5,
    name: "Blind Justice (Hævnens nat)",
    year: 1999,
    rating: 4.7,
    inTheaters: true,
  },
];

export const userList = [
  {
    id: 1,
    name: "Martelle",
    type: "USER",
    username: "mbowton0",
    age: 30,
    nationality: "Indonesia",
    friends: [
      {
        id: 2,
        name: "Riley",
        type: "USER",
        username: "reagers1",
        age: 29,
        nationality: "China",
      },
      {
        id: 3,
        name: "Cymbre",
        type: "USER",
        username: "cjeanet2",
        age: 24,
        nationality: "Russia",
      },
    ],
  },
  {
    id: 2,
    name: "Riley",
    type: "USER",
    username: "reagers1",
    age: 29,
    nationality: "China",
  },
  {
    id: 3,
    name: "Cymbre",
    type: "USER",
    username: "cjeanet2",
    age: 24,
    nationality: "Russia",
  },
  {
    id: 4,
    name: "Stacy",
    type: "USER",
    username: "sdamp3",
    age: 59,
    nationality: "Norway",
  },
  {
    id: 5,
    name: "Ulises",
    type: "USER",
    username: "ucadden4",
    age: 59,
    nationality: "China",
  },
  {
    id: 6,
    name: "Odilia",
    type: "USER",
    username: "opilcher5",
    age: 21,
    nationality: "Indonesia",
  },
  {
    id: 7,
    name: "Imojean",
    type: "USER",
    username: "ielcy6",
    age: 55,
    nationality: "Russia",
  },
  {
    id: 8,
    name: "Madella",
    type: "USER",
    username: "mantrobus7",
    age: 52,
    nationality: "China",
  },
  {
    id: 9,
    name: "Roch",
    type: "USER",
    username: "rpeschet8",
    age: 53,
    nationality: "China",
  },
  {
    id: 10,
    name: "Cristiano",
    type: "USER",
    username: "cpurchase9",
    age: 63,
    nationality: "Philippines",
  },
  {
    id: 11,
    name: "Hieronymus",
    type: "USER",
    username: "hashcrofta",
    age: 32,
    nationality: "South Sudan",
  },
  {
    id: 12,
    name: "Ariella",
    type: "USER",
    username: "alambertciorwynb",
    age: 44,
    nationality: "Russia",
  },
  {
    id: 13,
    name: "Hillary",
    type: "USER",
    username: "hwicksonc",
    age: 51,
    nationality: "Indonesia",
  },
  {
    id: 14,
    name: "Blake",
    type: "USER",
    username: "bcrootd",
    age: 33,
    nationality: "Poland",
  },
  {
    id: 15,
    name: "Jack",
    type: "USER",
    username: "jmorrisone",
    age: 59,
    nationality: "Ireland",
  },
];
