export const userList = [
  {
    id: 1,
    name: "Martelle",
    username: "mbowton0",
    age: 30,
    nationality: "Indonesia",
  },
  {
    id: 2,
    name: "Riley",
    username: "reagers1",
    age: 29,
    nationality: "China",
  },
  {
    id: 3,
    name: "Cymbre",
    username: "cjeanet2",
    age: 24,
    nationality: "Russia",
  },
  {
    id: 4,
    name: "Stacy",
    username: "sdamp3",
    age: 59,
    nationality: "Norway",
  },
  {
    id: 5,
    name: "Ulises",
    username: "ucadden4",
    age: 59,
    nationality: "China",
  },
  {
    id: 6,
    name: "Odilia",
    username: "opilcher5",
    age: 21,
    nationality: "Indonesia",
  },
  {
    id: 7,
    name: "Imojean",
    username: "ielcy6",
    age: 55,
    nationality: "Russia",
  },
  {
    id: 8,
    name: "Madella",
    username: "mantrobus7",
    age: 52,
    nationality: "China",
  },
  {
    id: 9,
    name: "Roch",
    username: "rpeschet8",
    age: 53,
    nationality: "China",
  },
  {
    id: 10,
    name: "Cristiano",
    username: "cpurchase9",
    age: 63,
    nationality: "Philippines",
  },
  {
    id: 11,
    name: "Hieronymus",
    username: "hashcrofta",
    age: 32,
    nationality: "South Sudan",
  },
  {
    id: 12,
    name: "Ariella",
    username: "alambertciorwynb",
    age: 44,
    nationality: "Russia",
  },
  {
    id: 13,
    name: "Hillary",
    username: "hwicksonc",
    age: 51,
    nationality: "Indonesia",
  },
  {
    id: 14,
    name: "Blake",
    username: "bcrootd",
    age: 33,
    nationality: "Poland",
  },
  {
    id: 15,
    name: "Jack",
    username: "jmorrisone",
    age: 59,
    nationality: "Ireland",
  },
];
